"""
src/portfolio/event_regional.py
===============================
GENERATED by .stageW4_calib.py + .stageW4_emit.py — do not hand-edit.

Regional benchmark returns and HK/SG sector anchors for every crisis event
in event_library.EVENTS, computed from live FMP EOD on 2026-08-27.

Two kinds of number live here, and they are NOT equivalent:

  REGIONAL_BENCHMARKS_DATA — real index returns (^HSI, ^HSCE, ^STI). FMP
      carries these back to 1986/1993/1987, which is what makes the pre-2000
      windows computable at all.

  REGIONAL_SECTORS — cap-weighted baskets of the largest CURRENT constituents
      of each sector on the exchange. Neither HKEX nor SGX has sector ETFs
      with usable history, so there is no index to quote. These therefore
      carry SURVIVORSHIP BIAS: the basket is drawn from companies still
      listed today, so a sector whose worst names delisted reads better than
      it lived. Every row records its constituent count, and the events that
      use them carry an explicit caveat.

Coverage is reported honestly rather than zero-filled. Notably:

  * asian_fc_1997 has NO HK or SG sector rows. FMP's HK single-name history
    begins 2000-01-03 for essentially every name, and too few SGX names
    listed before 1997 survive to clear the 5-constituent floor. The index
    benchmarks still cover the window, so an Asian holding anchors to ^HSI
    or ^STI rather than to a US sector ETF.
  * dotcom_2000 clears the floor in only a few sectors for the same reason.

Coverage guard matches the runtime engine in replay.py: a constituent needs
its first close within 14 days of the window start and at least
15 in-window closes, and a sector needs 5 covered constituents.
"""
from __future__ import annotations

# key -> {index label -> {return_pct, max_dd_pct}}
REGIONAL_BENCHMARKS_DATA: dict[str, dict[str, dict]] = {
    "asian_fc_1997": {
        "HSI": {"return_pct": -47.6, "max_dd_pct": -60.1},
        "HSCEI": {"return_pct": -62.8, "max_dd_pct": -86.5},
        "STI": {"return_pct": -52.3, "max_dd_pct": -59.5},
    },
    "china_crackdown_2021": {
        "HSI": {"return_pct": -52.8, "max_dd_pct": -52.8},
        "HSCEI": {"return_pct": -59.6, "max_dd_pct": -59.6},
        "STI": {"return_pct": 7.6, "max_dd_pct": -13.8},
    },
    "china_crash_2015": {
        "HSI": {"return_pct": -32.0, "max_dd_pct": -32.3},
        "HSCEI": {"return_pct": -45.2, "max_dd_pct": -45.2},
        "STI": {"return_pct": -24.3, "max_dd_pct": -24.9},
    },
    "covid_2020": {
        "HSI": {"return_pct": -21.5, "max_dd_pct": -21.5},
        "HSCEI": {"return_pct": -19.8, "max_dd_pct": -21.6},
        "STI": {"return_pct": -26.2, "max_dd_pct": -27.8},
    },
    "dotcom_2000": {
        "HSI": {"return_pct": -49.7, "max_dd_pct": -51.1},
        "HSCEI": {"return_pct": 10.8, "max_dd_pct": -39.1},
        "STI": {"return_pct": -42.2, "max_dd_pct": -43.8},
    },
    "euro_2011": {
        "HSI": {"return_pct": -28.8, "max_dd_pct": -29.0},
        "HSCEI": {"return_pct": -35.8, "max_dd_pct": -36.6},
        "STI": {"return_pct": -19.7, "max_dd_pct": -20.7},
    },
    "gfc_2008": {
        "HSI": {"return_pct": -59.8, "max_dd_pct": -65.2},
        "HSCEI": {"return_pct": -62.3, "max_dd_pct": -75.5},
        "STI": {"return_pct": -61.0, "max_dd_pct": -61.7},
    },
    "q4_2018": {
        "HSI": {"return_pct": -6.6, "max_dd_pct": -12.0},
        "HSCEI": {"return_pct": -6.8, "max_dd_pct": -9.3},
        "STI": {"return_pct": -5.2, "max_dd_pct": -9.2},
    },
    "rate_shock_2022": {
        "HSI": {"return_pct": -28.2, "max_dd_pct": -33.1},
        "HSCEI": {"return_pct": -30.5, "max_dd_pct": -35.2},
        "STI": {"return_pct": -4.4, "max_dd_pct": -11.7},
    },
    "svb_2023": {
        "HSI": {"return_pct": -6.1, "max_dd_pct": -8.3},
        "HSCEI": {"return_pct": -6.5, "max_dd_pct": -9.2},
        "STI": {"return_pct": -4.7, "max_dd_pct": -6.0},
    },
}

# key -> region -> [{sector, return_pct, constituents}], best->worst
REGIONAL_SECTORS: dict[str, dict[str, tuple]] = {
    "china_crackdown_2021": {
        "HK": (
            ("Energy", 15.6, 12),
            ("Industrials", -16.8, 9),
            ("Utilities", -17.1, 12),
            ("Real Estate", -24.1, 11),
            ("Financials", -30.6, 12),
            ("Technology", -45.3, 7),
            ("Consumer Staples", -45.7, 7),
            ("Communication Services", -46.1, 9),
            ("Materials", -46.7, 11),
            ("Health Care", -61.1, 9),
            ("Consumer Discretionary", -62.3, 9),
        ),
        "SG": (
            ("Consumer Discretionary", 19.9, 12),
            ("Financials", 18.9, 9),
            ("Industrials", 18.0, 12),
            ("Health Care", 1.0, 8),
            ("Materials", 0.8, 6),
            ("Real Estate", -15.1, 11),
            ("Consumer Staples", -17.7, 11),
            ("Technology", -27.5, 11),
        ),
    },
    "china_crash_2015": {
        "HK": (
            ("Communication Services", -16.6, 7),
            ("Utilities", -21.9, 12),
            ("Industrials", -24.5, 9),
            ("Real Estate", -29.7, 9),
            ("Consumer Discretionary", -31.8, 5),
            ("Technology", -34.7, 5),
            ("Materials", -36.1, 9),
            ("Financials", -41.3, 11),
            ("Energy", -44.8, 11),
        ),
        "SG": (
            ("Health Care", -4.8, 7),
            ("Technology", -12.3, 10),
            ("Consumer Staples", -13.1, 11),
            ("Real Estate", -13.9, 11),
            ("Consumer Discretionary", -14.4, 11),
            ("Industrials", -18.2, 12),
            ("Materials", -20.2, 6),
            ("Financials", -30.1, 8),
        ),
    },
    "covid_2020": {
        "HK": (
            ("Financials", -16.2, 12),
            ("Communication Services", -18.8, 8),
            ("Health Care", -21.4, 7),
            ("Real Estate", -23.9, 10),
            ("Utilities", -24.7, 12),
            ("Consumer Discretionary", -25.2, 7),
            ("Technology", -27.5, 6),
            ("Industrials", -28.2, 9),
            ("Energy", -29.2, 12),
            ("Materials", -34.3, 11),
        ),
        "SG": (
            ("Health Care", -19.5, 8),
            ("Financials", -30.4, 8),
            ("Industrials", -30.5, 12),
            ("Technology", -33.1, 10),
            ("Real Estate", -33.5, 11),
            ("Consumer Staples", -33.6, 11),
            ("Materials", -33.6, 6),
            ("Consumer Discretionary", -36.2, 12),
        ),
    },
    "dotcom_2000": {
        "HK": (
            ("Utilities", 32.8, 7),
            ("Real Estate", -0.3, 7),
        ),
        "SG": (
            ("Industrials", -17.5, 7),
            ("Financials", -27.0, 6),
            ("Consumer Discretionary", -38.9, 7),
        ),
    },
    "euro_2011": {
        "HK": (
            ("Utilities", -5.7, 10),
            ("Communication Services", -17.8, 6),
            ("Energy", -20.2, 11),
            ("Real Estate", -30.4, 8),
            ("Financials", -41.1, 11),
            ("Industrials", -48.2, 9),
            ("Materials", -48.4, 9),
        ),
        "SG": (
            ("Consumer Staples", -7.8, 9),
            ("Consumer Discretionary", -12.5, 9),
            ("Real Estate", -12.9, 10),
            ("Financials", -18.4, 8),
            ("Health Care", -19.7, 6),
            ("Materials", -21.9, 5),
            ("Technology", -22.6, 9),
            ("Industrials", -22.9, 11),
        ),
    },
    "gfc_2008": {
        "HK": (
            ("Utilities", -22.4, 9),
            ("Communication Services", -22.8, 6),
            ("Real Estate", -50.3, 8),
            ("Financials", -59.3, 9),
            ("Energy", -62.6, 10),
            ("Materials", -68.8, 7),
            ("Industrials", -69.0, 7),
        ),
        "SG": (
            ("Consumer Staples", -34.6, 8),
            ("Consumer Discretionary", -39.7, 9),
            ("Health Care", -45.2, 5),
            ("Industrials", -57.3, 10),
            ("Financials", -63.7, 8),
            ("Real Estate", -63.9, 8),
            ("Technology", -78.4, 9),
        ),
    },
    "q4_2018": {
        "HK": (
            ("Real Estate", -1.7, 10),
            ("Utilities", -1.7, 12),
            ("Materials", -1.8, 10),
            ("Communication Services", -2.7, 8),
            ("Industrials", -4.2, 9),
            ("Financials", -5.0, 12),
            ("Consumer Discretionary", -6.6, 6),
            ("Technology", -13.7, 6),
            ("Energy", -17.5, 11),
        ),
        "SG": (
            ("Consumer Discretionary", 0.2, 12),
            ("Real Estate", -1.3, 11),
            ("Industrials", -1.6, 12),
            ("Health Care", -1.6, 8),
            ("Materials", -4.0, 6),
            ("Financials", -4.5, 8),
            ("Consumer Staples", -5.2, 11),
            ("Technology", -9.1, 10),
        ),
    },
    "rate_shock_2022": {
        "HK": (
            ("Energy", 8.5, 12),
            ("Real Estate", -8.6, 11),
            ("Consumer Staples", -17.7, 7),
            ("Financials", -19.3, 12),
            ("Materials", -21.9, 11),
            ("Communication Services", -24.4, 11),
            ("Industrials", -25.2, 9),
            ("Consumer Discretionary", -29.7, 10),
            ("Technology", -30.9, 7),
            ("Utilities", -33.7, 12),
            ("Health Care", -43.6, 9),
        ),
        "SG": (
            ("Consumer Discretionary", 20.5, 12),
            ("Industrials", 7.2, 12),
            ("Financials", 0.8, 9),
            ("Materials", -1.3, 6),
            ("Real Estate", -10.5, 12),
            ("Consumer Staples", -11.5, 11),
            ("Health Care", -20.6, 8),
            ("Technology", -27.4, 12),
        ),
    },
    "svb_2023": {
        "HK": (
            ("Energy", 6.9, 12),
            ("Industrials", 0.0, 9),
            ("Financials", -0.1, 12),
            ("Consumer Staples", -0.4, 7),
            ("Communication Services", -1.2, 12),
            ("Technology", -1.4, 7),
            ("Materials", -1.5, 11),
            ("Utilities", -1.8, 12),
            ("Real Estate", -3.5, 12),
            ("Health Care", -6.4, 9),
            ("Consumer Discretionary", -11.7, 10),
        ),
        "SG": (
            ("Consumer Staples", -0.0, 11),
            ("Consumer Discretionary", -0.3, 12),
            ("Industrials", -0.6, 12),
            ("Health Care", -1.8, 8),
            ("Materials", -2.3, 6),
            ("Real Estate", -2.6, 12),
            ("Financials", -4.6, 10),
            ("Technology", -9.2, 12),
        ),
    },
}


# SPY/QQQ over the same windows — the hand-written EventSpec
# entries quote these; kept here so the source of every curated
# number is one generated file.
US_BENCHMARKS_DATA: dict[str, dict[str, dict]] = {
    "asian_fc_1997": {
        "SPY": {"return_pct": 13.9, "max_dd_pct": -19.0},
    },
    "china_crackdown_2021": {
        "SPY": {"return_pct": -1.6, "max_dd_pct": -25.4},
        "QQQ": {"return_pct": -16.8, "max_dd_pct": -35.5},
    },
    "china_crash_2015": {
        "SPY": {"return_pct": -12.9, "max_dd_pct": -14.1},
        "QQQ": {"return_pct": -11.2, "max_dd_pct": -16.4},
    },
    "covid_2020": {
        "SPY": {"return_pct": -34.1, "max_dd_pct": -34.1},
        "QQQ": {"return_pct": -28.1, "max_dd_pct": -28.6},
    },
    "dotcom_2000": {
        "SPY": {"return_pct": -36.7, "max_dd_pct": -36.7},
        "QQQ": {"return_pct": -76.1, "max_dd_pct": -76.1},
    },
    "euro_2011": {
        "SPY": {"return_pct": -19.3, "max_dd_pct": -19.3},
        "QQQ": {"return_pct": -13.3, "max_dd_pct": -16.1},
    },
    "gfc_2008": {
        "SPY": {"return_pct": -56.5, "max_dd_pct": -56.5},
        "QQQ": {"return_pct": -51.8, "max_dd_pct": -53.6},
    },
    "q4_2018": {
        "SPY": {"return_pct": -20.2, "max_dd_pct": -20.2},
        "QQQ": {"return_pct": -22.3, "max_dd_pct": -22.9},
    },
    "rate_shock_2022": {
        "SPY": {"return_pct": -25.4, "max_dd_pct": -25.4},
        "QQQ": {"return_pct": -34.6, "max_dd_pct": -34.6},
    },
    "svb_2023": {
        "SPY": {"return_pct": -6.0, "max_dd_pct": -6.9},
        "QQQ": {"return_pct": -3.3, "max_dd_pct": -6.6},
    },
}


# US SPDR sector returns for the Asia events, computed by
# .stageW4_us_sectors.py. The original seven keep their hand-curated rows
# (re-verified against these — every one inside the 8pp tolerance); only
# events with no curated US rows take these. asian_fc_1997 is absent
# because the sector SPDRs launched in December 1998, after the window.
US_SECTORS: dict[str, tuple] = {
    "china_crash_2015": (
        ("Utilities", "XLU", 7.4),
        ("Consumer Staples", "XLP", 2.7),
        ("Technology", "XLK", -9.3),
        ("Consumer Discretionary", "XLY", -10.5),
        ("Industrials", "XLI", -13.0),
        ("Health Care", "XLV", -14.7),
        ("Financials", "XLF", -21.5),
        ("Materials", "XLB", -22.7),
        ("Energy", "XLE", -30.0),
    ),
    "china_crackdown_2021": (
        ("Energy", "XLE", 93.6),
        ("Health Care", "XLV", 13.9),
        ("Consumer Staples", "XLP", 10.5),
        ("Utilities", "XLU", 7.7),
        ("Financials", "XLF", 5.5),
        ("Industrials", "XLI", 4.9),
        ("Materials", "XLB", -0.1),
        ("Real Estate", "XLRE", -3.3),
        ("Technology", "XLK", -6.6),
        ("Consumer Discretionary", "XLY", -15.5),
        ("Communication Services", "XLC", -34.5),
    ),
}
