"""Static SOTP assumptions snapshot — task #27 production lift.

Production runs attach the validated, trialed assumptions for covered
tickers when the live SOTP extractor produced no output for them (see
pipeline.py Phase 4.4). The artifact is ``src/data/sotp_assumptions_v1.json``,
generated by ``.stage7_snapshot_assumptions.py`` — a NOTE-mode extractor run
over the sharpened research fixtures (``tests/fixtures/sotp/research_note_*.txt``),
sanity-gated against the GS published TPs. Live extractor output always wins
over the snapshot when both exist.

Env controls:
  SOTP_SNAPSHOT_DISABLED   truthy -> loader returns {} (hard kill-switch)
  SOTP_SNAPSHOT_TICKERS    comma-separated allowlist (e.g. "BABA,JD")
                           restricting which snapshot entries apply;
                           unset = every ticker in the artifact.

Every failure mode (missing/corrupt artifact, disabled) returns {} so the
pipeline degrades to exact pre-task-#27 behavior: the DCF engine simply
adds no "SOTP (analyst)" method and the legacy IV is untouched.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

_DATA_PATH = Path(__file__).resolve().parents[2] / "data" / "sotp_assumptions_v1.json"


def _truthy(value: str | None) -> bool:
    return (value or "").strip().lower() in {"1", "true", "yes", "on"}


def load_sotp_snapshot(path: str | Path | None = None) -> dict:
    """Return ``{ticker: assumptions}`` from the snapshot artifact.

    ``path`` overrides the default artifact location (tests). Entries without
    a non-empty ``segments`` list are dropped defensively — an assumptions
    dict the engine cannot consume would only add noise downstream.
    """
    if _truthy(os.getenv("SOTP_SNAPSHOT_DISABLED")):
        return {}
    target = Path(path) if path else _DATA_PATH
    try:
        with open(target, encoding="utf-8") as fh:
            doc = json.load(fh)
    except (OSError, ValueError):
        return {}
    assumptions = doc.get("assumptions") if isinstance(doc, dict) else None
    if not isinstance(assumptions, dict):
        return {}
    allowed = os.getenv("SOTP_SNAPSHOT_TICKERS", "").strip()
    allow = ({t.strip().upper() for t in allowed.split(",") if t.strip()}
             if allowed else None)
    out: dict = {}
    for ticker, item in assumptions.items():
        if not isinstance(item, dict) or not item.get("segments"):
            continue
        if allow is not None and str(ticker).upper() not in allow:
            continue
        out[ticker] = item
    return out


def canonical_sotp_key(ticker: str) -> str:
    """Upper-cased, and HK codes in the repo's 5-digit form ("3690.HK" ->
    "03690.HK"). Snapshot keys and run tickers are compared on this key; a
    literal match left the "3690.HK" entry unreachable by any run."""
    t = (ticker or "").strip().upper()
    try:
        from src.tools.hk.ticker import is_hk_ticker, to_canonical
        if is_hk_ticker(t):
            return to_canonical(t)
    except Exception:
        pass
    return t


def _adr_alias(key: str) -> str | None:
    try:
        from src.tools.sec_segments import _ADR_FILER_ALIAS
        return _ADR_FILER_ALIAS.get(key)
    except Exception:
        return None


def lookup_snapshot(snapshot: dict, ticker: str) -> tuple[str | None, dict | None]:
    """(snapshot key, entry) for a ticker: exact, canonical, then the HK
    line's ADR (09988.HK -> BABA). Engine inputs are USD and per-share values
    divide by the run's own share count after USD->listing FX, so an ADR's
    assumptions serve its HK line without an ADS ratio."""
    if not snapshot:
        return None, None
    if snapshot.get(ticker):
        return ticker, snapshot[ticker]
    by_key = {canonical_sotp_key(k): k for k in snapshot}
    key = canonical_sotp_key(ticker)
    for candidate in (key, _adr_alias(key)):
        if candidate and candidate in by_key:
            return by_key[candidate], snapshot[by_key[candidate]]
    return None, None


def attach_snapshot(existing: dict | None, snapshot: dict,
                    tickers: list) -> tuple[dict, list]:
    """Merge snapshot assumptions into the run's ``sotp_assumptions`` dict.

    Returns ``(merged, attached)`` where ``attached`` lists the tickers that
    received a snapshot entry. Live extractor output already present in
    ``existing`` always wins — the snapshot only fills gaps, so a production
    run with ``sotp_enabled`` / licensed PDFs keeps its live-extracted
    assumptions untouched. ``existing`` is never mutated.
    """
    merged = dict(existing or {})
    attached: list = []
    for ticker in tickers:
        if merged.get(ticker):
            continue
        snap_key, snap = lookup_snapshot(snapshot, ticker)
        if not snap:
            continue
        # _origin marks the entry as validated snapshot input, so the live
        # plausibility gate in dcf_agent never second-guesses it.
        merged[ticker] = {**snap, "_origin": f"snapshot:{snap_key}"}
        attached.append(ticker)
    return merged, attached
